spring:
  datasource:
    url: jdbc:sqlserver://192.168.0.18:1433;databaseName=neoBay_formal_20170108;useUnicode=true;characterEncoding=GBK
    username: sa
    password: password1.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialize: false
  jpa:
    database: sql_server
    database-platform: SQL_SERVER
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect