spring:
  datasource:
    url: jdbc:sqlserver://123.59.50.191:1433;databaseName=neoBay
    username: sa
    password: qiyewan2016
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialize: false
  jpa:
    database: sql_server
    database-platform: SQL_SERVER
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: